# Generated by Django 3.2.18 on 2023-02-24 12:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                ("summary", models.TextField()),
                ("link", models.URLField()),
                ("pub_at", models.DateField()),
            ],
        ),
    ]
